### ISSUE TITLE
Can't convert CS:GO models to S&Box.

### ISSUE THREAD

**Issue by haayfe** [kristiker/source1import#23]
Was trying to convert materials, models, particles, sounds and scripts to Source 2 for S&BOX but it gave me the error that it couldn't find any .mdl files even though they are present in the files. Not really sure what's going wrong here but would appreciate it if you could let me know what to do. Thanks very much!

**Comment by kristiker** [comment]
It's already mentioned at #20. You will need to download an older version of s&box, compile the models and then update to latest s&box.
