### ISSUE TITLE
$ssbump support?

### ISSUE THREAD

**Issue by Validator2** [kristiker/source1import#5]
At least in S&Box, there is a "Enable Self-Shadow" feature, as far as I can tell, it solves most inconsistencies...
https://developer.valvesoftware.com/wiki/$ssbump

F_ENABLE_NORMAL_SELF_SHADOW 1
g_flLightRangeForSelfShadowNormals "1.000"

This is how I set mine to in order to properly display them, the default that sbox sets g_flLightRangeForSelfShadowNormals to is .707

**Comment by kristiker** [comment]
Sure I could enable it. I left it disabled for HL:A because $ssbump doesn't work there although the parameter is present.

**Comment by Validator2** [comment]
I can upload some examples, sure! Would you like them here, or on a different platform? I'd prefer discord if that's okay...

**Comment by kristiker** [comment]
Here works. Unless they changed the complex shader, the old version of s&box that I have should do the job.

**Comment by Validator2** [comment]
![image](https://user-images.githubusercontent.com/61028955/158532930-6b9be553-4bfd-47ef-837c-0293869031e4.png)
[lab_metalwall02_vmt.txt](https://github.com/kristiker/source1import/files/8259547/lab_metalwall02_vmt.txt)
[lab_metalwall02_vmat.txt](https://github.com/kristiker/source1import/files/8259548/lab_metalwall02_vmat.txt)

I think this should be enough information...
Would you like me to create a new issue for every unique sbox shader? (at least the ones that I can understand)

**Comment by kristiker** [comment]
Yeah issues are welcome. Did you try to put it as a bent normal, perhaps looks better that way ingame. Or is it better this way? Always best to test the materials in a test map.

**Comment by Validator2** [comment]
I'm not sure either... but maybe someday someone else will step in and correct us haha
