### ISSUE TITLE
Texture Importing uses smallest mipmap

### ISSUE THREAD

**Issue by thesentrycoder** [kristiker/source1import#51]
When exporting a vtf that has mipmaps to source2, source1import either exports all mipmaps as the same file, replacing the correct file everytime, or just exports the smallest mipmap. Major issue for map porting, plz fix.

**Comment by kristiker** [comment]
I don't think this is true for most materials. Maybe you ran into a special case?

**Comment by thesentrycoder** [comment]
aye yes, maybe it's just Goldeneye Source being a massive b&^h, like always...
