### ISSUE TITLE
Issue converting SFM materials to Source 2 materials (vmat)

### ISSUE THREAD

**Issue by GrupoLinea2** [kristiker/source1import#59]
When i´m exporting the vmt files from Source Filmmaker to vmat this error happens: 

![imagen_2023-05-24_230923931](https://github.com/kristiker/source1import/assets/134553534/ecf249f4-c220-4fed-a77e-8589db422527)

**Comment by kristiker** [comment]
For now you can take the vmt file that is next in alphabetical order to cartel_anden and save it in notepad with UTF 8 encoding

**Comment by GrupoLinea2** [comment]
Wow! It works. Thanks!!!

**Comment by GrupoLinea2** [comment]
That's weird. I exported a texture folder from the sfm a long time ago and it worked everything perfectly but now I've tried again after a while and it gives me the same mistake. How do the materials folders have to be placed?

**Comment by GrupoLinea2** [comment]
Okay, I'm stupid 😂 🤦 . Turns out the error was parameters in certain vmt files that had intruding letters like the Ñ or accents. Removing them, I've already been able to export everything without problems. I apologize for opening the issue again

**Comment by kristiker** [comment]
Yeah great
