### ISSUE TITLE
There seems to be a problem importing sky material from Half-Life 2.

### ISSUE THREAD

**Issue by pzC6L4g** [kristiker/source1import#6]
Only a few sky materials can be imported properly and a few textures can be converted:
Successfully converted material:
sky_borealis01
sky_day01_01
sky_day01_01_hdr
sky_day01_04
sky_day01_04_hdr
sky_day01_05
sky_day01_05_hdr
sky_day01_06
sky_day01_06_hdr
sky_day01_07
sky_day01_07_hdr
sky_day01_08

**Comment by kristiker** [comment]
Thanks! I think it should work now.
